name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master  # Adjust if your default branch is different
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Adjust to your .NET version

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Deploy to Azure Static Web Apps
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/BlazorWAzure.Client'  # Adjust to your app's path
          api_location: '/BlazorWAzure.Functions'      # Adjust to your API's path
          output_location: 'wwwroot'             # Adjust if different

